server:
  port: 9000

eureka:
  server:
    enable-self-preservation: false # 开发环境关闭自我保护。 Warning
    eviction-interval-timer-in-ms: 10000 # 剔除服务间隔，单位/ms
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # 是否将自己注册到注册中心,根据需要开启/关闭
    fetch-registry: false # 是否从Eureka中获取注册信息,根据需要开启/关闭
    service-url: # Eureka Client 的请求地址, localhost:9000
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
#      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}:${server.port}/eureka

spring:
  application:
    name: EUREKA-SERVER

# ref: https://www.cnblogs.com/ouyida3/p/9747423.html
#security:                         # 开启服务注册认证机制
#  basic:
#    enabled: true                 # 是否开启认证，默认true，需开启时可省略。
#  user:
#    name: eureka                  # 认证时，使用的用户名
#    password: eureka              # 认证时，使用的密码
