server:
  port: 9003
spring:
  application:
    name: SERVICE-CONSUMER # 服务名称
  cloud:
    loadbalancer:
      retry:
        enabled: true # 重试开关 默认 true
eureka:
  client:
    service-url: # 刚刚在Eureka Server 配置的请求地址
      defaultZone: http://localhost:9000/eureka/ # ,http://localhost:9100/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 自定义注册ID为ip:端口的格式
    lease-renewal-interval-in-seconds: 5 #发送心跳的间隔
    lease-expiration-duration-in-seconds: 10 #续约到期时间

# 可以通过 服务名：ribbon:NFLoadBalancerRuleClassName: 对应的策略全类名
SERVICE-PROVIDER:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    ConnectTimeout: 250 # 与服务提供方建立Http连接的超时时间
    ReadTimeout: 1000 # 接收返回数据的超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数(包含第一次请求，即配置1相当于请求超时就切换)

# feign的配置
feign:
  client:
    config:
      SERVICE-PROVIDER:
        loggerLevel: FULL # NONE(默认选项), BASIC, HEADERS, FULL; 内容依次丰富、性能影响依次增大
logging:
  level:
    cn.keats.service_consumer.feign.UserServiceFeignClient: debug
